name: Compose Node React Template

on:
  push:
    branches:
      - main
    paths:
      - clients/react/**
      - servers/node/**
      - .github/workflows/**
      - docs/**
      - README.md

jobs:
  compose-template:
    name: Compose Template
    if: ${{ !(contains(github.repository, 'template'))  }}
    uses: ./.github/workflows/compose-and-redact-template.yml
    with:
      client: react
      server: node
      prefix: billing
      suffix: ilt
    secrets:
      token: ${{ secrets.WORKFLOW_TOKEN }}
      copybara_ssh_key: ${{ secrets.COPYBARA_KEY }}
      bot_name: ${{ secrets.APP_NAME }}
      bot_email: ${{ secrets.APP_EMAIL }}
